### ISSUE TITLE
Application Error when specifying DGCG configuration in application.yml

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-issuance-service#48]
## Describe the bug

After removing the comments in the application.yml file, and even though the gateway.connector.enabled is set to **false**, the application fails to start with an error message.

```
dgc:
  gateway:
    connector:
      enabled: false
#      endpoint: https://dgc-gateway.example.com
#      proxy:
#        enabled: false
#      max-cache-age: 300
#      tls-trust-store:
#        password: dgcg-p4ssw0rd
#        path: classpath:tls_trust_store.p12
#      tls-key-store:
#        alias: 1
#        password: dgcg-p4ssw0rd
#        path: classpath:tls_key_store.p12
#      trust-anchor:
#        alias: ta
#        password: dgcg-p4ssw0rd
#        path: classpath:trust_anchor.jks
```

Error:
```
2021-05-07 20:01:20.431 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'client' defined in class path resource [eu/europa/ec/dgc/gateway/connector/client/DgcGatewayConnectorRestClientConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.Client]: Factory method 'client' threw exception; nested exception is java.io.FileNotFoundException: class path resource [tls_trust_store.p12] cannot be resolved to absolute file path because it does not exist
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at eu.europa.ec.dgc.issuance.DgcIssuanceApplication.main(DgcIssuanceApplication.java:45) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[app.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.Client]: Factory method 'client' threw exception; nested exception is java.io.FileNotFoundException: class path resource [tls_trust_store.p12] cannot be resolved to absolute file path because it does not exist
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.5.jar!/:5.3.5]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.5.jar!/:5.3.5]
        ... 28 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [tls_trust_store.p12] cannot be resolved to absolute file path because it does not exist
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:177) ~[spring-core-5.3.5.jar!/:5.3.5]
        at eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClientConfig.getSslContext(DgcGatewayConnectorRestClientConfig.java:83) ~[dgc-lib-0.4.0.jar!/:na]
        at eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClientConfig.client(DgcGatewayConnectorRestClientConfig.java:66) ~[dgc-lib-0.4.0.jar!/:na]
        at eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClientConfig$$EnhancerBySpringCGLIB$$2d78b7dc.CGLIB$client$0(<generated>) ~[dgc-lib-0.4.0.jar!/:na]
        at eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClientConfig$$EnhancerBySpringCGLIB$$2d78b7dc$$FastClassBySpringCGLIB$$9d2e4602.invoke(<generated>) ~[dgc-lib-0.4.0.jar!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.5.jar!/:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.5.jar!/:5.3.5]
        at eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClientConfig$$EnhancerBySpringCGLIB$$2d78b7dc.client(<generated>) ~[dgc-lib-0.4.0.jar!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.5.jar!/:5.3.5]
```

## Expected behaviour

Application should be able to run without errors

## Steps to reproduce the issue

Uncomment the dgc.gateway.connector section in application.yml
Compile and run.

## Technical details

- Host Machine OS
```
- uname -a
Linux FLATRO 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

## Additional context

**Versions:** 
https://github.com/eu-digital-green-certificates/dgca-issuance-service/tree/0.0.13
https://github.com/eu-digital-green-certificates/dgc-lib/tree/0.4.0

**Comment by a-trzewik** [comment]
Please read the error messages. 
java.io.FileNotFoundException: class path resource [tls_trust_store.p12] cannot be resolved to absolute file path because it does not exist
You have configured that the file 'tls_trust_store.p12' should be read but the file is not existing.

If you uncomment the section you need to ensure that the parameters are correct
so the path to keystores need to be correct.
It is commented out because we can not provide valid keys to get access to getaway on github.

The configuration part are comming from connector dgc-lib
https://github.com/eu-digital-green-certificates/dgc-lib
read the docu for more information

**Comment by psavva** [comment]
Hi @a-trzewik   Please review the configuration again one more time....
If you review the stepsm I have uncomment, the config, and run. Since the connector is false, it should not try to connect and should certianly not fail to run...

dgc:
  gateway:
    connector:
      **enabled: false**

If the dgc.gateway.connector = false, how is it that that the dgc-lib is still trying to be invoked by the issuer?
I think this should be fixed, hence raised this bug.

In addition, the application.yaml is also missing the upload-key-store:

      upload-key-store:
        alias: upload
        password: <password>
        path:classpath:upload.p12

**Comment by psavva** [comment]
May I suggest you re-open based on this info I have provided.
